# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
      DB_USERNAME: dama
      DB_PASSWORD: dama2021
      DB_NAME: dama_db
    volumes:
        - ./mongo_scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        - ./mongodbdata:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1234
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - backend

  dama-api:
    image: myfirstdocker01/dama-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - backend
      - frontend

  dama-ui:
    image: myfirstdocker01/dama-ui
    ports:
      - 8082:80
    restart: always
    depends_on:
      - dama-api
    networks:
      - frontend

networks:
  backend:
  frontend: