logging:
  level:
    root: info

spring:
  data:
    mongodb:
      database: dama
      port: 27017

mongock:
  change-logs-scan-package:
    - com.dama.ohrringe.config.db.migrations
server:
  servlet:
    context-path: /earringApi

