jwtSecret: javaDama2021secretEarringApplicationMilkaBelarussecretDeutschDublikateaDama2021secretEarringAppl

logging:
  level:
    root: debug

spring:
  data:
    mongodb:
      database: dama
      port: 27017
#      host: localhost
      host: mongo


mongock:
  change-logs-scan-package:
    - com.dama.ohrringe.config.db.migrations
server:
  servlet:
    context-path: /earringApi
  port: 8080


